spring.application.name=backend
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_USERNAME}?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

eth.rpc-url=${ETH_RPC_URL}
eth.chain-id=${ETH_CHAIN_ID}
eth.private-key=${ETH_PRIVATE_KEY}

pinata.jwt=${PINATA_JWT}
pinata.api.base=${PINATA_API_BASE}
pinata.gateway.base=${PINATA_GATEWAY_BASE}

minio.endpoint=${MINIO_ENDPOINT_EXTERNAL}
minio.access.key=${MINIO_ACCESS_KEY}
minio.secret.key=${MINIO_SECRET_KEY}
minio.secure=${MINIO_SECURE}
minio.bucket=${MINIO_BUCKET}

contract.nft=${CONTRACT_ADDRESS}

app.firebase.configuration-file=classpath:firebase-service-account.json

spring.jpa.hibernate.ddl-auto=update

spring.jackson.time-zone=Asia/Seoul
